//! Build the skill distribution bundles once, here, and embed them. Both the
//! server download endpoint and the Desktop local Skill Library depend on this
//! crate, so they embed the SAME deterministic archives — identical bytes and
//! SHA-256 on every surface.

use std::path::{Path, PathBuf};
use std::process::Command;

fn emit_rerun_for_tree(dir: &Path) {
    if let Ok(entries) = std::fs::read_dir(dir) {
        for entry in entries.flatten() {
            let path = entry.path();
            if path.is_dir() {
                emit_rerun_for_tree(&path);
            } else {
                println!("cargo:rerun-if-changed={}", path.display());
            }
        }
    }
}

fn main() {
    let manifest_dir = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap());
    let root = manifest_dir
        .parent()
        .and_then(|p| p.parent())
        .expect("repo root is two levels above crates/skill-bundles")
        .to_path_buf();

    let script = root.join("scripts/build_skill_bundles.py");
    println!("cargo:rerun-if-changed={}", script.display());
    for dependency in [
        "scripts/credential_scan.py",
        "scripts/skill_bundle_files.py",
        "scripts/skill-bundle-files.txt",
        "Cargo.toml",
    ] {
        println!("cargo:rerun-if-changed={}", root.join(dependency).display());
    }
    emit_rerun_for_tree(&root.join("skill/agent-room"));
    emit_rerun_for_tree(&root.join("skill/loca-care"));

    // Build into Cargo's per-build OUT_DIR (isolated), so a concurrent build,
    // packaging test, or CI job never clobbers this build's output.
    let out_dir = PathBuf::from(std::env::var("OUT_DIR").unwrap());
    let bundle_dir = out_dir.join("skill-bundles");
    let python = ["python3", "python"]
        .into_iter()
        .find(|candidate| Command::new(candidate).arg("--version").output().is_ok())
        .expect("Python 3 is required to build the skill bundles");
    let status = Command::new(python)
        .arg(&script)
        .arg(&bundle_dir)
        .current_dir(&root)
        .status()
        .unwrap_or_else(|e| {
            panic!(
                "failed to run {}: {e} (Python 3 is required to build the skill bundles)",
                script.display()
            )
        });
    assert!(status.success(), "{} failed", script.display());

    let names = ["loca", "loca-care"];
    let mut generated = String::from(
        "// @generated by build.rs — the embedded skill distribution bundles.\n\
         pub struct Bundle {\n\
         \x20   pub name: &'static str,\n\
         \x20   pub zip: &'static [u8],\n\
         \x20   pub manifest: &'static str,\n\
         }\n\
         pub static BUNDLES: &[Bundle] = &[\n",
    );
    for name in names {
        let zip = bundle_dir.join(format!("{name}.zip"));
        let manifest = bundle_dir.join(format!("{name}.manifest.json"));
        assert!(zip.exists(), "missing bundle {}", zip.display());
        assert!(manifest.exists(), "missing manifest {}", manifest.display());
        generated.push_str(&format!(
            "    Bundle {{ name: {name:?}, zip: include_bytes!({zip:?}), manifest: include_str!({manifest:?}) }},\n",
            zip = zip.display().to_string(),
            manifest = manifest.display().to_string(),
        ));
    }
    generated.push_str("];\n");

    let out = out_dir.join("skill_bundles_data.rs");
    std::fs::write(&out, generated).expect("write generated skill bundle table");
}
